// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1DKtKiMkuQAAZWtZzTFyG0DXR60YdwI',
    appId: '1:738586610292:web:b77e0e7018fd946517df21',
    messagingSenderId: '738586610292',
    projectId: 'math-app-ea77f',
    authDomain: 'math-app-ea77f.firebaseapp.com',
    storageBucket: 'math-app-ea77f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0StA_n8XXx2Bl4Ed98ZD9plaKwCiaL5o',
    appId: '1:738586610292:android:77a988e885d1d78717df21',
    messagingSenderId: '738586610292',
    projectId: 'math-app-ea77f',
    storageBucket: 'math-app-ea77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-Sd_v3aRau4_ZWX2Z476U4WJc5trrTA',
    appId: '1:738586610292:ios:3bf0559c30417a3a17df21',
    messagingSenderId: '738586610292',
    projectId: 'math-app-ea77f',
    storageBucket: 'math-app-ea77f.appspot.com',
    iosBundleId: 'com.example.mathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-Sd_v3aRau4_ZWX2Z476U4WJc5trrTA',
    appId: '1:738586610292:ios:3bf0559c30417a3a17df21',
    messagingSenderId: '738586610292',
    projectId: 'math-app-ea77f',
    storageBucket: 'math-app-ea77f.appspot.com',
    iosBundleId: 'com.example.mathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1DKtKiMkuQAAZWtZzTFyG0DXR60YdwI',
    appId: '1:738586610292:web:bc290bdf3fbe820d17df21',
    messagingSenderId: '738586610292',
    projectId: 'math-app-ea77f',
    authDomain: 'math-app-ea77f.firebaseapp.com',
    storageBucket: 'math-app-ea77f.appspot.com',
  );
}
